# Generated by Django 2.0.2 on 2018-03-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0002_auto_20180301_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='Name',
        ),
        migrations.AddField(
            model_name='license',
            name='Lid',
            field=models.CharField(default='unlicensed', help_text='type Licence name here', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='license',
            name='Propreitor',
            field=models.CharField(default='owner', help_text='type owner name here', max_length=20),
        ),
        migrations.AddField(
            model_name='license',
            name='ShopName',
            field=models.CharField(default='girvi dukan', help_text='type Shop name Here', max_length=50),
        ),
        migrations.AlterField(
            model_name='license',
            name='Address',
            field=models.TextField(help_text='type License address here'),
        ),
    ]
