# Generated by Django 2.0.2 on 2018-03-01 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0003_auto_20180301_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='loanbill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bill', serialize=False, to='girvi.LoanBill'),
        ),
    ]
