# Generated by Django 2.0.2 on 2018-03-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0004_auto_20180301_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Area',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ContactNo',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='EmailId',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='RelatedAs',
            field=models.CharField(choices=[('S/o', 'S/o'), ('D/o', 'D/o'), ('W/o', 'W/o')], default='S/o', max_length=3),
        ),
    ]
