# Generated by Django 2.0.2 on 2018-03-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0005_auto_20180301_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanbill',
            name='ItemValue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
