# Generated by Django 2.0.2 on 2018-03-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0006_auto_20180301_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ContactNo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
