# Generated by Django 2.0.2 on 2018-03-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0007_auto_20180301_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Address',
            field=models.TextField(default='address here'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Area',
            field=models.CharField(default='area here', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ContactNo',
            field=models.CharField(default='911', max_length=10),
        ),
    ]
