# Generated by Django 2.0.2 on 2018-03-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0008_auto_20180301_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='RelatedTo',
            field=models.CharField(default='Relation/name', max_length=20),
        ),
    ]
