# Generated by Django 2.0.2 on 2018-03-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0011_auto_20180301_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanbill',
            name='ItemDesc',
            field=models.TextField(default='items here'),
        ),
    ]
