# Generated by Django 2.0.2 on 2018-03-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0012_auto_20180302_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanbill',
            name='ItemWeight',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=7),
        ),
        migrations.AlterField(
            model_name='loanbill',
            name='LoanAmount',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=7),
        ),
        migrations.AlterField(
            model_name='loanbill',
            name='LoanInt',
            field=models.DecimalField(decimal_places=2, default='2', max_digits=7),
        ),
    ]
