# Generated by Django 2.0.2 on 2018-03-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0014_auto_20180302_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanbill',
            name='ItemType',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze'), ('O', 'Other')], default='Gold', max_length=6),
        ),
    ]
