# Generated by Django 2.0.2 on 2018-03-04 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0015_auto_20180302_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='loanbill',
            options={'ordering': ['-LoanDate']},
        ),
    ]
